name: "Action for testing"
description: "An action for testing pocs"

inputs:
  token:
    description: "Github token"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Welcome"
      shell: bash
      run: |
        echo "Welcome ${{ github.event.workflow_run.head_branch }}"
        if [ ${{ inputs.token }} -eq "" ]
        then
          echo "Hello"
        fi
